/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Class.*;
import Model.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mario
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    AeropuertoModel aeropuerto_model = new AeropuertoModel();
    ArrayList <Aeropuerto> listaAeropuertos = aeropuerto_model.Read();
    ArrayList <Avion> listaAviones = new ArrayList();
    ArrayList <Ruta> listaRutas = new ArrayList();


    public Index() {
        initComponents();
        cargarListaTablaAerouertos();
    }
    
    public void cargarListaTablaAerouertos() {
        DefaultTableModel tab = new DefaultTableModel();
        String[] cabecera = {"Id", "Nombre", "Pais", "Ciudad", "CoordX", "CoordY"};
        Object[] datos = new Object[cabecera.length];
        tab.setColumnIdentifiers(cabecera);
        for (int i = 0; i < listaAeropuertos.size(); i++) {
            datos[0] = listaAeropuertos.get(i).getId();
            datos[1] = listaAeropuertos.get(i).getNombre();
            datos[2] = listaAeropuertos.get(i).getPais();
            datos[3] = listaAeropuertos.get(i).getCiudad();
            datos[4] = listaAeropuertos.get(i).getCoord_x();
            datos[5] = listaAeropuertos.get(i).getCoord_y();
            tab.addRow(datos);
        }
        tableAeropuertos.setModel(tab);
    } 
    
    public void limpiarCamposAeropuerto(){
        txtIdAeropuerto.setValue(0);
        txtNombreAeropuerto.setText("");
        txtPaisAeropuerto.setText("");
        txtCiudadAeropuerto.setText("");
        txtCoordXAeropuerto.setValue(0);
        txtCoordYAoerpuerto.setValue(0);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jSpinner1 = new javax.swing.JSpinner();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabAeropuerto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdAeropuerto = new javax.swing.JSpinner();
        txtNombreAeropuerto = new javax.swing.JTextField();
        txtPaisAeropuerto = new javax.swing.JTextField();
        txtCiudadAeropuerto = new javax.swing.JTextField();
        txtCoordXAeropuerto = new javax.swing.JSpinner();
        txtCoordYAoerpuerto = new javax.swing.JSpinner();
        btnGuardarAeropuerto = new javax.swing.JButton();
        btnBuscarAeropuerto = new javax.swing.JButton();
        btnEditarAeropuerto = new javax.swing.JButton();
        btnEliminarAeropuerto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAeropuertos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtModeloAvion = new javax.swing.JTextField();
        txtIdAvion = new javax.swing.JSpinner();
        btnGuardarAvion = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("id");

        jLabel2.setText("nombre");

        jLabel3.setText("pais");

        jLabel4.setText("ciudad");

        jLabel5.setText("Coord X");

        jLabel6.setText("Coord Y");

        btnGuardarAeropuerto.setText("Guardar");
        btnGuardarAeropuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAeropuertoActionPerformed(evt);
            }
        });

        btnBuscarAeropuerto.setText("Buscar");
        btnBuscarAeropuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAeropuertoActionPerformed(evt);
            }
        });

        btnEditarAeropuerto.setText("Editar");
        btnEditarAeropuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAeropuertoActionPerformed(evt);
            }
        });

        btnEliminarAeropuerto.setText("Eliminar");
        btnEliminarAeropuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAeropuertoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabAeropuertoLayout = new javax.swing.GroupLayout(tabAeropuerto);
        tabAeropuerto.setLayout(tabAeropuertoLayout);
        tabAeropuertoLayout.setHorizontalGroup(
            tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAeropuertoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(23, 23, 23)
                .addGroup(tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPaisAeropuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txtCiudadAeropuerto)
                    .addComponent(txtCoordXAeropuerto)
                    .addComponent(txtCoordYAoerpuerto)
                    .addComponent(txtIdAeropuerto)
                    .addComponent(txtNombreAeropuerto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardarAeropuerto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarAeropuerto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarAeropuerto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarAeropuerto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(74, 74, 74))
        );
        tabAeropuertoLayout.setVerticalGroup(
            tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAeropuertoLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardarAeropuerto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAeropuertoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPaisAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(tabAeropuertoLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnBuscarAeropuerto)))
                .addGap(18, 18, 18)
                .addGroup(tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCiudadAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditarAeropuerto))
                .addGroup(tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAeropuertoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCoordXAeropuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tabAeropuertoLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnEliminarAeropuerto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabAeropuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCoordYAoerpuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aeropuerto", tabAeropuerto);

        tableAeropuertos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableAeropuertos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ListarAeropuertos", jPanel2);

        jLabel8.setText("id");

        jLabel9.setText("modelo");

        btnGuardarAvion.setText("Guardar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtModeloAvion)
                    .addComponent(txtIdAvion, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(btnGuardarAvion)
                .addGap(56, 56, 56))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtIdAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarAvion))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtModeloAvion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Avion", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ListarAviones", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ruta", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ListarRutas", jPanel6);

        jLabel7.setText("Sistema de gestion de Aerolineas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarAeropuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAeropuertoActionPerformed
        // Accedo a los valores del formulario
        int id = (int) txtIdAeropuerto.getValue(); // Spiner
        String nombre = txtNombreAeropuerto.getText(); // Text Field
        String ciudad = txtCiudadAeropuerto.getText();
        String pais = txtPaisAeropuerto.getText();
        int coord_x = (int) txtCoordXAeropuerto.getValue();
        int coord_y = (int) txtCoordYAoerpuerto.getValue();
        //Valido que los valores no esten vacios
        if(id == 0 || nombre.equals("") || ciudad.equals("") || pais.equals("") 
                || coord_x == 0 || coord_y == 0){
            JOptionPane.showMessageDialog(null, "Error: debe llenar todos los campos");
        }else{
            //Creo un objeto y lo agrego a una lista de Aeropuertos
            Aeropuerto aero = new Aeropuerto(id, nombre, ciudad, pais, coord_x, coord_y);
            aeropuerto_model.Create(aero);
            listaAeropuertos.add(aero);
            JOptionPane.showMessageDialog(this, "Aeropuerto " + nombre + " fue creado correctamente");
            cargarListaTablaAerouertos();
            limpiarCamposAeropuerto();
        }        
    }//GEN-LAST:event_btnGuardarAeropuertoActionPerformed

    private void btnBuscarAeropuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAeropuertoActionPerformed
        // TODO add your handling code here:
        int id = (int) txtIdAeropuerto.getValue();
        boolean existe = false; 
        for (int i = 0; i < listaAeropuertos.size(); i++) {
            if (listaAeropuertos.get(i).getId() == id) { 
                txtNombreAeropuerto.setText(listaAeropuertos.get(i).getNombre());  //TExtField
                txtCiudadAeropuerto.setText(listaAeropuertos.get(i).getCiudad());
                txtPaisAeropuerto.setText(listaAeropuertos.get(i).getPais());
                txtCoordXAeropuerto.setValue(listaAeropuertos.get(i).getCoord_x()); // Spinner
                txtCoordYAoerpuerto.setValue(listaAeropuertos.get(i).getCoord_y());
                existe = true;
                break;
            }
        }
        if (!existe) {
            JOptionPane.showMessageDialog(this, "El Aeropuerto no esta registrado");
        }
    }//GEN-LAST:event_btnBuscarAeropuertoActionPerformed

    private void btnEditarAeropuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAeropuertoActionPerformed
        // TODO add your handling code here:        
        int id = (int) txtIdAeropuerto.getValue(); // Spiner
        String nombre = txtNombreAeropuerto.getText(); // Text Field
        String ciudad = txtCiudadAeropuerto.getText();
        String pais = txtPaisAeropuerto.getText();
        int coord_x = (int) txtCoordXAeropuerto.getValue();
        int coord_y = (int) txtCoordYAoerpuerto.getValue();
        boolean existe = false;
        //Valido que los valores no esten vacios
        if(id == 0 || nombre.equals("") || ciudad.equals("") || pais.equals("") 
                || coord_x == 0 || coord_y == 0){
            JOptionPane.showMessageDialog(null, "Error: debe llenar todos los campos");
        }else{
            for (int i = 0; i < listaAeropuertos.size(); i++) {
            if (listaAeropuertos.get(i).getId() == id) {
                    listaAeropuertos.get(i).setNombre(nombre);
                    listaAeropuertos.get(i).setCiudad(ciudad);
                    listaAeropuertos.get(i).setPais(pais);
                    listaAeropuertos.get(i).setCoord_x(coord_x);
                    listaAeropuertos.get(i).setCoord_y(coord_y);
                    existe = true;
                    cargarListaTablaAerouertos();
                    JOptionPane.showMessageDialog(this, "Aeropuerto editado correctamente");
                    limpiarCamposAeropuerto();
                    break;
                }
            }
        }
        if (!existe) {
            JOptionPane.showMessageDialog(this, "El Aeropuerto no esta registrado");
        }        
    }//GEN-LAST:event_btnEditarAeropuertoActionPerformed

    private void btnEliminarAeropuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAeropuertoActionPerformed
        // TODO add your handling code here:        
        int id = (int) txtIdAeropuerto.getValue(); // Spiner
        boolean existe = false;
        for (int i = 0; i < listaAeropuertos.size(); i++) {
            if (listaAeropuertos.get(i).getId() == id) {
                    listaAeropuertos.remove(listaAeropuertos.get(i));
                    JOptionPane.showMessageDialog(this, "Aeropuerto eliminado correctamente");
                existe = true;
                cargarListaTablaAerouertos();
                limpiarCamposAeropuerto();
                break;
            }
        }
        if (!existe) {
            JOptionPane.showMessageDialog(this, "El Aeropuerto no esta registrado");
        }
        
    }//GEN-LAST:event_btnEliminarAeropuertoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAeropuerto;
    private javax.swing.JButton btnEditarAeropuerto;
    private javax.swing.JButton btnEliminarAeropuerto;
    private javax.swing.JButton btnGuardarAeropuerto;
    private javax.swing.JButton btnGuardarAvion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel tabAeropuerto;
    private javax.swing.JTable tableAeropuertos;
    private javax.swing.JTextField txtCiudadAeropuerto;
    private javax.swing.JSpinner txtCoordXAeropuerto;
    private javax.swing.JSpinner txtCoordYAoerpuerto;
    private javax.swing.JSpinner txtIdAeropuerto;
    private javax.swing.JSpinner txtIdAvion;
    private javax.swing.JTextField txtModeloAvion;
    private javax.swing.JTextField txtNombreAeropuerto;
    private javax.swing.JTextField txtPaisAeropuerto;
    // End of variables declaration//GEN-END:variables
}
